### PR TITLE
Micro-Reddit (Project: Building With Active Record)

### PR DESCRIPTION
**Pull request by SarvarKh**
## We have built a mini-Reddit version of the popular social news website.

In this app, users can:
- post whatever they like;
- comment on each other's post; 

through the terminal.

### CODE REVIEW

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @SarvarKh 
Such a remarkable project you made :+1: ! Awesome README :100: !
We, however, do have a few changes to carry out before we proceed (see review comment).

##

Kindly work on the suggested changes 👇.
- [ ] `post` model is not covering the tests
- [ ] Please add some test cases in the README file
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by SarvarKh** [comment]
# Hi @umairarshadbutt
Thank you for your swift review and comments :+1: 

Can you specify what kind of tests are you referring to?
I have checked them in my terminal, see screenshot below.
Screenshot from 2021-01-29 18-42-01

**Comment by umairarshadbutt** [comment]
Hi @SarvarKh 
When I was saving the data in the table by using `u1.save` and `p1.save,` so it was not working for `p1.save`.

**Comment by SarvarKh** [comment]
@umairarshadbutt, I am not sure why it gave an error in your PC. I have rechecked one more time. Creating and saving both u1 and p1 as well.
Both have been saved successfully.

See the screenshot below.
Screenshot from 2021-01-29 19-09-38

I believe you have included all attributes while creating a post object and saving it in the DB? 
Because it contains:
- title
- description
- user_id

**Comment by umairarshadbutt** [comment]
Hi @SarvarKh 
It's great :+1: . You can submit the PR again for review.

**Review by enaburekhan — APPROVED** [review]
# Status: Project Approve :heavy_check_mark:
Hi team!
Congratulations!  :clap::clap:the project has met all the requirements and is hereby approved :muscle:. Great job guys!!!

You can go ahead and merge the pull request. And don't forget to submit a project completion form.

You can reach me on slack @ Eric Enaburekhan if you have any questions
Happy Coding :blush:
Eric Enaburekhan

**Pull request merged**
